input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    add_field => { "ingest_source" => "logstash-tcp" }
  }
}

output {
  elasticsearch {
    hosts => [ "${ELASTICSEARCH_HOST}" ]
    user => "${ELASTICSEARCH_USER}"
    password => "${ELASTICSEARCH_PASSWORD}"
    index => "app-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }
  stdout {
    codec => rubydebug
  }
}
