spring.application.name=demoElasticSearch
server.port=8080

elasticsearch.url=${ELASTICSEARCH_URL:http://localhost:9200}
elasticsearch.username=${ELASTICSEARCH_USERNAME:elastic}
elasticsearch.password=${ELASTICSEARCH_PASSWORD:elastic}
elasticsearch.sample-index=${ELASTICSEARCH_SAMPLE_INDEX:sample-index}
elasticsearch.logs-index-pattern=${ELASTICSEARCH_LOGS_INDEX_PATTERN:app-logs-*}
elasticsearch.index-init-enabled=${ELASTICSEARCH_INDEX_INIT_ENABLED:true}

management.tracing.sampling.probability=1.0

logging.level.org.elasticsearch.client=INFO
logging.level.co.elastic.clients=INFO
